apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: go-tvcpbtpp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-tvcpbtpp 
  name: go-tvcpbtpp
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: go-tvcpbtpp 
